- name: Zip Release
  # You may pin to the exact commit or the version.
  # uses: TheDoctor0/zip-release@a1afcab9c664c9976ac398fa831eac67bed1eb0e
  uses: TheDoctor0/zip-release@0.4.1
  with:
    # Filename for archive
    filename: # default is release.zip
    # Base path for archive files
    path: # optional, default is .
    # Working directory before zipping
    directory: # optional, default is .
    # List of excluded files / directories
    exclusions: # optional, default is 
    # Tool to use for archiving
    type: # optional, default is zip
